"""create interview monitor table

Revision ID: 1ca028e27209
Revises: bc1c3c33520c
Create Date: 2026-07-24 17:49:55.265010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1ca028e27209'
down_revision: Union[str, Sequence[str], None] = 'bc1c3c33520c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_monitor_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('filler_count', sa.Integer(), nullable=True),
    sa.Column('fluency_score', sa.Float(), nullable=True),
    sa.Column('dominant_emotion', sa.String(), nullable=False),
    sa.Column('eye_contact_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_monitor_reports_id'), 'interview_monitor_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_interview_monitoring_id'), table_name='interview_monitoring')
    op.drop_table('interview_monitoring')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_monitoring',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('emotion', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('eye_contact', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('filler_words', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fluency_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('overall_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], name=op.f('interview_monitoring_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_monitoring_pkey'))
    )
    op.create_index(op.f('ix_interview_monitoring_id'), 'interview_monitoring', ['id'], unique=False)
    op.drop_index(op.f('ix_interview_monitor_reports_id'), table_name='interview_monitor_reports')
    op.drop_table('interview_monitor_reports')
    # ### end Alembic commands ###
