"""add feedback fields

Revision ID: 41f759f33adf
Revises: 1ca028e27209
Create Date: 2026-07-25 08:37:18.138620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41f759f33adf'
down_revision: Union[str, Sequence[str], None] = '1ca028e27209'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_monitor_reports', sa.Column('confidence_score', sa.Float(), nullable=True))
    op.add_column('interview_monitor_reports', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('interview_monitor_reports', sa.Column('strengths', sa.JSON(), nullable=True))
    op.add_column('interview_monitor_reports', sa.Column('weaknesses', sa.JSON(), nullable=True))
    op.add_column('interview_monitor_reports', sa.Column('suggestions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_monitor_reports', 'suggestions')
    op.drop_column('interview_monitor_reports', 'weaknesses')
    op.drop_column('interview_monitor_reports', 'strengths')
    op.drop_column('interview_monitor_reports', 'summary')
    op.drop_column('interview_monitor_reports', 'confidence_score')
    # ### end Alembic commands ###
