"""add skills column

Revision ID: 9249bfe80fd8
Revises: 9f0e8567e176
Create Date: 2026-07-08 12:10:39.906045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9249bfe80fd8'
down_revision: Union[str, Sequence[str], None] = '9f0e8567e176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('skills', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'skills')
    # ### end Alembic commands ###
