"""create interview conversations table

Revision ID: d23514bb44ad
Revises: 0c802f0f31fd
Create Date: 2026-08-01 09:41:13.464006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd23514bb44ad'
down_revision: Union[str, Sequence[str], None] = '0c802f0f31fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_conversations_id'), 'interview_conversations', ['id'], unique=False)
    op.create_index(op.f('ix_interview_conversations_session_id'), 'interview_conversations', ['session_id'], unique=False)
    op.alter_column('interview_monitor_snapshots', 'second',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.drop_constraint(op.f('interview_sessions_resume_id_fkey'), 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'interview_sessions', 'resumes', ['resume_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_sessions', type_='foreignkey')
    op.create_foreign_key(op.f('interview_sessions_resume_id_fkey'), 'interview_sessions', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    op.alter_column('interview_monitor_snapshots', 'second',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_index(op.f('ix_interview_conversations_session_id'), table_name='interview_conversations')
    op.drop_index(op.f('ix_interview_conversations_id'), table_name='interview_conversations')
    op.drop_table('interview_conversations')
    # ### end Alembic commands ###
